#!/usr/bin/ruby

###
# Author : Muhammad Quwais Saputra
# © Muhammad Quwais Saputra 2021
###

require 'ipaddr'
require 'iplocate'

def is_ip?(ip)
  !!IPAddr.new(ip) rescue false
end

def c(ip)
  results= IPLocate.lookup(ip)
  print "\033[36m#{results["country"]}\t\t\033[31m#{results["city"]}\n"
end

def smaki(ip)
  if is_ip?(ip) == true
    print "\033[32m#{ip}\t"
    c(ip)
  else
  end
end
o = [(1..9)].map(&:to_a).flatten

loop do
  h1 = (0...2).map { o[rand(o.length)] }.join
  h2 = (0...3).map { o[rand(o.length)] }.join
  h3 = (0...3).map { o[rand(o.length)] }.join
  h4 = (0...2).map { o[rand(o.length)] }.join

  b = "#{h1}.#{h2}.#{h3}.#{h4}"
  begin
    smaki(b)
  rescue Interrupt
    exit(1)
  end
end
