#!/usr/bin/ruby

###
# Author : Muhammad Quwais Saputra
# © Muhammad Quwais Saputra 2021
###

require 'ipaddr'
require 'iplocate'

def is_ip?(ip)
  !!IPAddr.new(ip) rescue false
end

def c(ip)
  results= IPLocate.lookup(ip)
  print "#{results["country"]}\t\t#{results["city"]}\n"
end

def smaki(ip)
  if is_ip?(ip) == true
    print "#{ip}\t"
    c(ip)
  else
  end
end
o = [(1..9)].map(&:to_a).flatten
puts "\n\n"
loop do
  # sori h1 gua apus
  # ini berguna buat scan yg kita inginkan aja. soalnya kalo IP nya
  # ngacak, berarti kita ga puas pake alat yang lu buat ini
  h2 = (0...3).map { o[rand(o.length)] }.join
  h3 = (0...3).map { o[rand(o.length)] }.join
  h4 = (0...2).map { o[rand(o.length)] }.join

  # males bat komen gua 
  b = "#{ARGV[0]}.#{h2}.#{h3}.#{h4}"
  begin
    smaki(b)
  rescue Interrupt
    puts "\n\n"
    exit(1)
  end
end
